apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app.kubernetes.io/name: checkout-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: checkout-postgres