apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
spec:
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - port: 8080
      targetPort: 8080
